version: 2.1
jobs:
  build:
    docker:
      - image: maierbn/opendihu:latest
    environment:
      FOO: bar
    parallelism: 3
    resource_class: large
    working_directory: /workspace/opendihu
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world"
      - run: make release

