version: 2
jobs:
  build:
    docker:
      - image: maierbn/opendihu:latest

    working_directory: /opendihu/opendihu

    steps:
      - checkout

      - run:
          command: apt-get update -y; apt-get upgrade -y; make release

