version: 2.1


jobs:
  build:
    docker:
      - image: maierbn/opendihu:latest
    environment:
      FOO: bar
    parallelism: 3
    resource_class: large
    working_directory: /workspace/opendihu
    branches:
      only:
        - develop
    steps:
      - run: make release

