version: 2
jobs:
  build:
    docker:
      - image: maierbn/opendihu:latest

    working_directory: /opendihu/opendihu

    steps:
      - checkout

      - run:
          command: sudo apt-get update && sudo apt-get upgrade && make release

